spring:
  application:
    name: service-producer
server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone:  http://peer1:8000/eureka/  
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2 