spring:
  application:
    name: service-zuul
server:
  port: 9008
  
zuul:
  routes:
    api-a: 
      path: /index/**
      serviceId: service-producer  

eureka:
  client:
    serviceUrl:
      defaultZone:  http://peer1:8000/eureka/  
  