spring:
  application:
    name: eureka-server

server:
  port: 8000
  
eureka:
  instance:
    hostname: localhost
    #hostname: peer1
  client:
  #集群部署时该项配置应该为true,或者注释掉，默认为true
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      #单机部署
      defaultZone:  http://localhost:${server.port}/eureka/
      #集群部署
      #defaultZone:  http://peer2:8001/eureka/,http://peer3:8002/eureka/
          
    